### ISSUE TITLE
bundle size

### ISSUE THREAD

**Issue by pozh** [antonreshetov/vue-unicons#10]
For some reason no matter how many icons are imported, the way shown  in your "cart", package size in my bundle is 400+K, just like all icons are imported

**Comment by antonreshetov** [comment]
I think you did something wrong. Perhaps you have your own build configuration

![test](https://user-images.githubusercontent.com/17480987/53224047-6172b080-3684-11e9-8e49-78c218c808f6.gif)

**Comment by pozh** [comment]
Thanks a lot for taking a look, it seems you are right, and that's my configs' issue.

**Comment by xperator** [comment]
I just started using this library and I have the same issue. I copied the vue 2 example code from readme file ( which imports only 2 icons ) but the `webpack-bundle-analyzer` is showing `icons.js` is a big 2.17MB ( 594.98 KB Gzipped )

@pozh Do you mind sharing how you solved the issue ?

**Comment by pozh** [comment]
> @pozh Do you mind sharing how you solved the issue ?
switched to SVGs and svg-to-vue-component lib

**Comment by xperator** [comment]
@pozh Hm... don't quite get it... what do you mean you switched to SVGs ? I thought this library uses svg by default.
I wonder if this is an issue with my laravel mix/webpack setup... I can't figure out what though. It seems the individual import is not working and instead whole content from `vue-unicons/dist/icons`  is imported...

**Comment by pozh** [comment]
@xperator I stopped using any lib containing icons. I'm simply using separate svgs instead
