### ISSUE TITLE
how to use with vuetify input

### ISSUE THREAD

**Issue by jimmiejackson414** [antonreshetov/vue-unicons#11]
Hi there,

Thanks for the incredible library!

Had a question (forgive me, I'm relatively new to the Vue world). I'm using Vuetify inputs and part of their api is to pass a prop to use icons as such: 

`prepend-icon='constructor'`

How would I go about adding the unicon with all of its props as an icon to a Vuetify input?

**Comment by antonreshetov** [comment]
Hi @jimmiejackson414 
Unfortunately, pass Vue-unicons as props no way.
If Vuetify provide slot for icons, then possible pass into slot `<unicon name="iconName"/>`

**Comment by jimmiejackson414** [comment]
No problem, thank you for your response!
