### ISSUE TITLE
NPM audit security report

### ISSUE THREAD

**Issue by Tuginho** [antonreshetov/vue-unicons#12]
I saw this when auditing my npm packages:

>   Critical        Command Injection                                             
>                                                                                 
>   Package         open                                                          
>                                                                                 
>   Patched in      >0.0.5                                                        
>                                                                                 
>   Dependency of   vue-unicons                                                   
>                                                                                 
>   Path            vue-unicons >                                                 
>                   e25a510fcb3da933736e6860a53583ace2a3dd0d98fbeced95aaaedd959…  
>                   > fontello-cli > open                                         
>                                                                                 
>   More info       https://npmjs.com/advisories/663

**Comment by antonreshetov** [comment]
Vue-unicons depends on [unicons](https://github.com/iconscout/unicons) and this vulnerability is in unicons dependencies. In this case it is not possible to eliminate the vulnerability in the Vue-unicons repository

You can run `npm audit fix` to fix the vulnerability.

You can also report this vulnerability to unicons [issue](https://github.com/iconscout/unicons/issues).

**Comment by Tuginho** [comment]
Understood. Thank you! Can be closed then
