### ISSUE TITLE
Even importing only necessary icons it still imports everything

### ISSUE THREAD

**Issue by DaniloNR** [antonreshetov/vue-unicons#18]
Hi, im having a issue: 

When I import each icon, it still imports everything... 
My import code: 

`import Unicon from 'vue-unicons'
import {
  uniSubject, uniApps, uniCommentAlt, uniBell, uniExit, uniSearch,
  uniPlusCircle, uniCheck, uniTimes, uniAngleDown, uniAngleDoubleLeft,
  uniAngleDoubleRight, uniArrowUp, uniArrowDown, uniBox, uniFileDownloadAlt,
  uniMoon, uniBrightnessEmpty, uniTextSize, uniTextFields
} from 'vue-unicons/src/icons'

Unicon.add([
  uniSubject, uniApps, uniCommentAlt, uniBell, uniExit, uniSearch,
  uniPlusCircle, uniCheck, uniTimes, uniAngleDown, uniAngleDoubleLeft,
  uniAngleDoubleRight, uniArrowUp, uniArrowDown, uniBox, uniFileDownloadAlt,
  uniMoon, uniBrightnessEmpty, uniTextSize, uniTextFields
])
Vue.use(Unicon)`
My bundle analizer shows that vue-unicons is **almost 1/3** (roughly 600kb) of my entire project :(

Im using the latest @vue/cli PWA template

![image](https://user-images.githubusercontent.com/6722669/63517950-5f1fd080-c4c6-11e9-806b-2b262402bee1.png)

**Comment by antonreshetov** [comment]
Closed because it was in 228efe1905168617993791fbad284cde8a51e20e
