### ISSUE TITLE
missing an undo icon

### ISSUE THREAD

**Issue by renerdias** [antonreshetov/vue-unicons#25]
Suggestion:

```<path d="M 9.042 4.406 C 8.791 4.391 8.523 4.48 8.287 4.717 L 4.287 8.717 C 4.195 8.812 4.125 8.924 4.078 9.047 C 3.978 9.29 3.978 9.565 4.078 9.808 C 4.125 9.931 4.195 10.043 4.287 10.139 L 8.287 14.139 C 8.678 14.533 9.317 14.533 9.708 14.139 C 10.103 13.747 10.103 13.108 9.708 12.717 L 7.408 10.428 L 16.997 10.428 C 17.55 10.428 17.997 10.875 17.997 11.428 L 17.997 16.596 C 17.997 17.148 17.55 17.596 16.997 17.596 L 11.152 17.594 C 10.125 17.593 10.078 19.59 11.15 19.592 L 16.997 19.595 C 18.654 19.595 19.997 18.252 19.997 16.595 L 19.997 11.428 C 19.997 9.771 18.654 8.428 16.997 8.428 L 7.408 8.428 L 9.708 6.139 C 10.418 5.429 9.797 4.45 9.042 4.406 Z"/>```

**Comment by hmaesta** [comment]
You should be asking Iconscout, not here. https://github.com/Iconscout/unicons

But you can always add a custom icon.
