### ISSUE TITLE
Custom icons issues with v2

### ISSUE THREAD

**Issue by NexPB** [antonreshetov/vue-unicons#27]
Hello Anton,

The release of v2.0.0 introduced a few bugs when adding custom icons:

- First of all the documentation to create a new custom icon const is out of date, as it now requires a `style` attribute as well
- There's no way to set the `viewBox` on the svg as it is now inside a container (it will set the viewbox on the container)

Thanks – great library otherwise!

**Comment by Edmund1645** [comment]
Hey @NexPB do your own custom icons appear?

For me, the `<svg><svg/>` tag appear but the `<path/>` child does not.

**Comment by NexPB** [comment]
@Edmund1645 Yes - the path child does appear for me. You probably forgot to set the style attr that is missing from the documentation.

```javascript
export const MyIcon = {
  name: 'my-icon',
  style: 'line',
  path: '<path />'
};

export default {
  MyIcon
};
```

**Comment by antonreshetov** [comment]
@NexPB It seems that you cannot just pass the attribute `viewBox` because the compiler converts it into `viewbox`. I can add this as `props`, I can also add perhaps an attribute binding to <svg> by adding `v-bind="$attrs"` for other needs.

**Comment by antonreshetov** [comment]
@NexPB please check latest release - https://github.com/antonreshetov/vue-unicons/releases/tag/v2.1.0

**Comment by NexPB** [comment]
@antonreshetov looking good thanks a lot! 🙏
