### ISSUE TITLE
Unicons not packaged for distribution

### ISSUE THREAD

**Issue by davestewart** [antonreshetov/vue-unicons#34]
Hey @antonreshetov,

It seems that the package is not packaged for distribution:

![image](https://user-images.githubusercontent.com/132681/83267956-d94f5500-a1bc-11ea-9c5c-bd5a76131d03.png)

Really, only the core files should be sent up to NPM (absolutely not node modules!) and the demo files should be managed separately (folder or repo).

I've got quite a bit of experience in packaging libs. Would you like some help?

Additionally, I think the main component could be rebuilt as a functional component with a render function, which would optimise it for speed. Could do this at the same time.

LMK.

**Comment by antonreshetov** [comment]
This library is called `vue-unicons` not `unicons`.  [Unicons](https://github.com/iconscout/unicons) is an dependency.

**Comment by davestewart** [comment]
OK, you both need to package your libs then:

![image](https://user-images.githubusercontent.com/132681/83276639-d0fd1700-a1c8-11ea-92ec-ce77f7b1a160.png)

**Comment by antonreshetov** [comment]
Maybe we shouldn't say that someone owes something? It's quite common for a library to have a source. Example - https://github.com/ElemeFE/element
