### ISSUE TITLE
Vue 3 and Typescript Problem

### ISSUE THREAD

**Issue by halilyuce** [antonreshetov/vue-unicons#40]
Hello mate, thanks for repo. I could not add this plugin to my vue 3 + typescript project. Can you add main.ts import example please ? thanks in advance :)

```
import { createApp } from "vue";
import App from "./App.vue";
import router from "./router";
import store from "./store";

createApp(App)
  .use(store)
  .use(router)
  .mount("#app");
```

**Comment by geopic** [comment]
I wrote the types file, can you post the code where you are getting the error?

**Comment by antonreshetov** [comment]
Duplicate of #39
