### ISSUE TITLE
Missing icon 'elipsis-double-v-alt'

### ISSUE THREAD

**Issue by GideonRoose** [antonreshetov/vue-unicons#44]
Hey,

First off, awesome work, I've used vue-unicons for 3 projects and it works like a charm. Just here to note that the `elipsis-double-v-alt` icon is missing. I've now added it as a custom icon, so it's not a problem really, but figured I'd give a note of it anyway.

**Comment by antonreshetov** [comment]
@GideonRoose vue unicons provides only those icons that are part of the free version of unicons.

**Comment by GideonRoose** [comment]
@antonreshetov I understand, but this particular icon is in fact part of the (free) line style collection.

**Comment by antonreshetov** [comment]
@GideonRoose 
<img width="657" alt="image" src="https://user-images.githubusercontent.com/17480987/112488595-b7980d80-8d8e-11eb-9e3d-a549689764a1.png">

**Comment by antonreshetov** [comment]
@GideonRoose I just push new release, in which I updated unicons to 3.0.6. In this release new icons have been added, as well as this missing icon. Please try it.

**Comment by antonreshetov** [comment]
Closed because it was add in 44c055be6271d158c92c30ef72a6ad0bcef9f36b
