### ISSUE TITLE
Build error with vite: "openBlock' is not exported"

### ISSUE THREAD

**Issue by sheoak** [antonreshetov/vue-unicons#49]
When building vue 3 app with vite, I get the following error with vue-unicons:

```
openBlock' is not exported by node_modules/vue-unicons/node_modules/vue/dist/vue.runtime.esm.js, imported by node_modules/vue-unicons/dist/vue-unicons.es.js
```

`node_modules/vue-unicons/dist/vue-unicons.es.js:1:7`

**Comment by antonreshetov** [comment]
@sheoak use `resolve: { dedupe: ['vue'] }` in `vite.config.js` or install `vue-unicons@next` which solved the problem. `vue` has been moved to `peerDependencies`.

**Comment by sheoak** [comment]
Thanks for the quick reply @antonreshetov !
It seems I can't install the next branch:
```
npm install --save vue-unicons@next
peer vue@"^2.5.22" from vue-unicons@3.2.2-alpha.1
```

**Comment by antonreshetov** [comment]
It's not a package issue. Try to remove node_modules and install again or use yarn.

**Comment by sheoak** [comment]
Yarn works but gives a warning:
`vue-unicons@3.2.2-alpha.1" has incorrect peer dependency "vue@^2.5.22".`

**Comment by the-prime-thanatos** [comment]
@antonreshetov The same problem in nuxt3:
```
import {defineNuxtPlugin} from '#app'
import Unicon from 'vue-unicons'
import { uniEye, uniEyeSlash, uniMultiply, uniTimes, uniMultiplyMonochrome, uniMultiplySolid } from 'vue-unicons/dist/icons'

export default defineNuxtPlugin((nuxtApp) => {
	Unicon.add([uniEye, uniEyeSlash, uniMultiply, uniTimes, uniMultiplyMonochrome, uniMultiplySolid]);
	nuxtApp.vueApp.use(Unicon);
})
```

"vue-unicons": "^3.2.2-alpha.1"
"nuxt3": "latest",

**Comment by mohammedmoutawakkil** [comment]
any solutions ?? i have the same problem
