### ISSUE TITLE
Save (floppy disk) icon

### ISSUE THREAD

**Issue by jsbroks** [antonreshetov/vue-unicons#5]
I'm considering switching my current project over to using these icons, but I need a `save` icon since it is a huge part of my application.

**Comment by antonreshetov** [comment]
Hi @jsbroks 
vue-unicons provides only those icons that are in the [original](https://github.com/iconscout/unicons) repo.
By the way, you can request the creation of the icon you need at [iconscout.com/unicons](https://iconscout.com/unicons#footer)

**Comment by jsbroks** [comment]
Thanks, my bad.
